2017-06-13T16:43:26.892796+00:00 app[web.1]: (0.000) SELECT "nutr_epacolo"."id", "nutr_epacolo"."ffdru", "nutr_epacolo"."fregid", "nutr_epacolo"."fsn", "nutr_epacolo"."lat", "nutr_epacolo"."slt", "nutr_epacolo"."loc", "nutr_epacolo"."county", "nutr_epacolo"."fips", "nutr_epacolo"."usps", "nutr_epacolo"."state", "nutr_epacolo"."country", "nutr_epacolo"."postal", "nutr_epacolo"."ffic", "nutr_epacolo"."fan", "nutr_epacolo"."tribe", "nutr_epacolo"."tln", "nutr_epacolo"."cdn", "nutr_epacolo"."huc", "nutr_epacolo"."region", "nutr_epacolo"."type", "nutr_epacolo"."desc", "nutr_epacolo"."cdate", "nutr_epacolo"."udate", "nutr_epacolo"."mex", "nutr_epacolo"."abbrev", "nutr_epacolo"."eit", "nutr_epacolo"."naics", "nutr_epacolo"."ntext", "nutr_epacolo"."sic", "nutr_epacolo"."sict", "nutr_epacolo"."lati", "nutr_epacolo"."long", "nutr_epacolo"."conv", "nutr_epacolo"."hcmt", "nutr_epacolo"."ham", "nutr_epacolo"."rpn", "nutr_epacolo"."hrdn", "nutr_epacolo"."cdsn", "nutr_epacolo"."cbc" FROM "nutr_epacolo" LIMIT 21; args=()
2017-06-13T16:43:26.895315+00:00 app[web.1]: Exception while resolving variable 'parent_template' in template 'nutr/epacolo_list.html'.
2017-06-13T16:43:26.895318+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:26.895319+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:26.895320+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:26.921412+00:00 app[web.1]: (0.000) SELECT "nutr_epacolo"."id", "nutr_epacolo"."ffdru", "nutr_epacolo"."fregid", "nutr_epacolo"."fsn", "nutr_epacolo"."lat", "nutr_epacolo"."slt", "nutr_epacolo"."loc", "nutr_epacolo"."county", "nutr_epacolo"."fips", "nutr_epacolo"."usps", "nutr_epacolo"."state", "nutr_epacolo"."country", "nutr_epacolo"."postal", "nutr_epacolo"."ffic", "nutr_epacolo"."fan", "nutr_epacolo"."tribe", "nutr_epacolo"."tln", "nutr_epacolo"."cdn", "nutr_epacolo"."huc", "nutr_epacolo"."region", "nutr_epacolo"."type", "nutr_epacolo"."desc", "nutr_epacolo"."cdate", "nutr_epacolo"."udate", "nutr_epacolo"."mex", "nutr_epacolo"."abbrev", "nutr_epacolo"."eit", "nutr_epacolo"."naics", "nutr_epacolo"."ntext", "nutr_epacolo"."sic", "nutr_epacolo"."sict", "nutr_epacolo"."lati", "nutr_epacolo"."long", "nutr_epacolo"."conv", "nutr_epacolo"."hcmt", "nutr_epacolo"."ham", "nutr_epacolo"."rpn", "nutr_epacolo"."hrdn", "nutr_epacolo"."cdsn", "nutr_epacolo"."cbc" FROM "nutr_epacolo"; args=()
2017-06-13T16:43:26.895321+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [parent_template] in u"[{'None': None, 'True': True, 'False': False}, {'user': <SimpleLazyObject: <function <lambda> at 0x7fabb9d31230>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'ERROR': 40, 'SUCCESS': 25, 'WARNING': 30, 'INFO': 20}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fabb9d3b110>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fabb9c74550>, u'request': <WSGIRequest: GET '/epacolo/'>, u'csrf_token': <SimpleLazyObject: <function _get_val at 0x7fabb9cbeb90>>}, {}, {'epacolo_list': [<EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, '...(remaining elements truncated)...']}]"
2017-06-13T16:43:29.299421+00:00 app[web.1]: Exception while resolving variable 'is_paginated' in template 'nutr/epacolo_list.html'.
2017-06-13T16:43:29.299430+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:29.299431+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:29.299431+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:29.299434+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [is_paginated] in u'[{\'None\': None, \'True\': True, \'False\': False}, {\'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7fabb9bd5a90>>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'ERROR\': 40, \'SUCCESS\': 25, \'WARNING\': 30, \'INFO\': 20}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fabb9d3b110>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fabb9c74550>, u\'request\': <WSGIRequest: GET \'/epacolo/\'>, u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fabb9cbeb90>>}, {}, {\'epacolo_list\': [<EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, <EPAColo: EPAColo object>, \'...(remaining elements truncated)...\']}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n  <div class="row">\\n    \'>, <Block Node: nut_content. Contents: [<TextNode: u\'\\n        This is default \'>]>, <TextNode: u\'\\n    </section>\\n    <sect\'>, <Block Node: create_button. Contents: []>, <TextNode: u\'\\n    </section>\\n  </div>\\n\'>, <IfNode>, <TextNode: u\'\\n\'>]>}]'
2017-06-13T16:43:29.380800+00:00 heroku[router]: at=info method=GET path="/epacolo/" host=immense-temple-86427.herokuapp.com request_id=7abc81db-11a5-42b7-a58c-f71ce11b3ac5 fwd="98.245.117.182" dyno=web.1 connect=0ms service=2618ms status=200 bytes=672432 protocol=https
2017-06-13T16:43:29.559537+00:00 heroku[router]: at=info method=GET path="/static/site/normalize.css" host=immense-temple-86427.herokuapp.com request_id=babd566d-ca59-4f3e-ac07-e78ad70d7f57 fwd="98.245.117.182" dyno=web.1 connect=0ms service=9ms status=404 bytes=2530 protocol=https
2017-06-13T16:43:29.587364+00:00 heroku[router]: at=info method=GET path="/static/site/skeleton.css" host=immense-temple-86427.herokuapp.com request_id=8f38a247-f924-41c7-affe-6ca4456a9331 fwd="98.245.117.182" dyno=web.1 connect=0ms service=35ms status=404 bytes=2527 protocol=https
2017-06-13T16:43:29.584531+00:00 heroku[router]: at=info method=GET path="/static/site/style.css" host=immense-temple-86427.herokuapp.com request_id=7fd41dba-6651-4738-815a-22c64c7532ef fwd="98.245.117.182" dyno=web.1 connect=0ms service=34ms status=404 bytes=2518 protocol=https
2017-06-13T16:43:29.549636+00:00 app[web.1]: Not Found: /static/site/normalize.css
2017-06-13T16:43:29.554010+00:00 app[web.1]: Exception while resolving variable 'name' in template 'unknown'.
2017-06-13T16:43:29.554012+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:29.554013+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:29.554014+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:29.554015+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'nutr.urls.epacolo' from '/app/nutr/urls/epacolo.py'> (None:None) ^epacolo/>"
2017-06-13T16:43:29.554505+00:00 app[web.1]: Exception while resolving variable 'name' in template 'unknown'.
2017-06-13T16:43:29.554507+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:29.554508+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:29.554508+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:29.554509+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'nutr.urls.nutrdef' from '/app/nutr/urls/nutrdef.py'> (None:None) ^nutrdef/>"
2017-06-13T16:43:29.554996+00:00 app[web.1]: Exception while resolving variable 'name' in template 'unknown'.
2017-06-13T16:43:29.554998+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:29.554999+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:29.555000+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:29.555000+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'nutr.urls.nutdata' from '/app/nutr/urls/nutdata.py'> (None:None) ^nutdata/>"
2017-06-13T16:43:29.555491+00:00 app[web.1]: Exception while resolving variable 'name' in template 'unknown'.
2017-06-13T16:43:29.555493+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:29.555494+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:29.555494+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:29.555495+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'user.urls' from '/app/user/urls.py'> (user:dj-auth) ^user/>"
2017-06-13T16:43:29.558147+00:00 app[web.1]: Not Found: /static/site/skeleton.css
2017-06-13T16:43:29.568321+00:00 app[web.1]: Exception while resolving variable 'name' in template 'unknown'.
2017-06-13T16:43:29.568324+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:29.568325+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:29.568326+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:29.568329+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'nutr.urls.epacolo' from '/app/nutr/urls/epacolo.py'> (None:None) ^epacolo/>"
2017-06-13T16:43:29.576839+00:00 app[web.1]: Not Found: /static/site/style.css
2017-06-13T16:43:29.577362+00:00 app[web.1]: Exception while resolving variable 'name' in template 'unknown'.
2017-06-13T16:43:29.577364+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:29.577365+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:29.577366+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:29.577367+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'nutr.urls.nutrdef' from '/app/nutr/urls/nutrdef.py'> (None:None) ^nutrdef/>"
2017-06-13T16:43:29.577874+00:00 app[web.1]: Exception while resolving variable 'name' in template 'unknown'.
2017-06-13T16:43:29.577876+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:29.577877+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:29.577877+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:29.577878+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'nutr.urls.nutdata' from '/app/nutr/urls/nutdata.py'> (None:None) ^nutdata/>"
2017-06-13T16:43:29.581671+00:00 app[web.1]: Exception while resolving variable 'name' in template 'unknown'.
2017-06-13T16:43:29.581674+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:29.581675+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:29.581675+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:29.581680+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'nutr.urls.epacolo' from '/app/nutr/urls/epacolo.pyc'> (None:None) ^epacolo/>"
2017-06-13T16:43:29.582426+00:00 app[web.1]: Exception while resolving variable 'name' in template 'unknown'.
2017-06-13T16:43:29.582428+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:29.582428+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:29.582429+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:29.582430+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'nutr.urls.nutrdef' from '/app/nutr/urls/nutrdef.pyc'> (None:None) ^nutrdef/>"
2017-06-13T16:43:29.582497+00:00 app[web.1]: Exception while resolving variable 'name' in template 'unknown'.
2017-06-13T16:43:29.582499+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:29.582500+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:29.582501+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:29.582501+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'nutr.urls.nutdata' from '/app/nutr/urls/nutdata.pyc'> (None:None) ^nutdata/>"
2017-06-13T16:43:29.582960+00:00 app[web.1]: Exception while resolving variable 'name' in template 'unknown'.
2017-06-13T16:43:29.582962+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:29.582963+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:29.582963+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:29.582964+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'user.urls' from '/app/user/urls.pyc'> (user:dj-auth) ^user/>"
2017-06-13T16:43:29.583581+00:00 app[web.1]: Exception while resolving variable 'name' in template 'unknown'.
2017-06-13T16:43:29.583582+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:29.583583+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:29.583584+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:29.583585+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'user.urls' from '/app/user/urls.py'> (user:dj-auth) ^user/>"
2017-06-13T16:43:29.945364+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=immense-temple-86427.herokuapp.com request_id=2da012fe-c4e9-4e16-b788-6f48c1b4ad54 fwd="98.245.117.182" dyno=web.1 connect=0ms service=7ms status=404 bytes=2488 protocol=https
2017-06-13T16:43:29.937080+00:00 app[web.1]: Not Found: /favicon.ico
2017-06-13T16:43:29.940343+00:00 app[web.1]: Exception while resolving variable 'name' in template 'unknown'.
2017-06-13T16:43:29.940345+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:29.940346+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:29.940347+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:29.940348+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'nutr.urls.epacolo' from '/app/nutr/urls/epacolo.py'> (None:None) ^epacolo/>"
2017-06-13T16:43:29.940703+00:00 app[web.1]: Exception while resolving variable 'name' in template 'unknown'.
2017-06-13T16:43:29.940706+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:29.940705+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:29.940706+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:29.940707+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'nutr.urls.nutrdef' from '/app/nutr/urls/nutrdef.py'> (None:None) ^nutrdef/>"
2017-06-13T16:43:29.940970+00:00 app[web.1]: Exception while resolving variable 'name' in template 'unknown'.
2017-06-13T16:43:29.940972+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:29.940973+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:29.940973+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:29.940974+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'nutr.urls.nutdata' from '/app/nutr/urls/nutdata.py'> (None:None) ^nutdata/>"
2017-06-13T16:43:29.941265+00:00 app[web.1]: Exception while resolving variable 'name' in template 'unknown'.
2017-06-13T16:43:29.941268+00:00 app[web.1]: Traceback (most recent call last):
2017-06-13T16:43:29.941269+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
2017-06-13T16:43:29.941269+00:00 app[web.1]:     (bit, current))  # missing attribute
2017-06-13T16:43:29.941270+00:00 app[web.1]: VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'user.urls' from '/app/user/urls.py'> (user:dj-auth) ^user/>"
